#!/bin/bash
# Usage: curl https://raw.github.com/nuada/puppet/master/apply | bash -s

# Install puppet
if [[ ! $(dpkg -l puppet 2> /dev/null) ]]; then
	. /etc/lsb-release
	wget http://apt.puppetlabs.com/puppetlabs-release-${DISTRIB_CODENAME}.deb
	dpkg -i puppetlabs-release-${DISTRIB_CODENAME}.deb
	rm -rf puppetlabs-release-${DISTRIB_CODENAME}.deb
	apt-get update
	apt-get -y install puppet
	puppet module install puppetlabs/stdlib
fi

# If not running from repo clone it
if [[ $0 == 'bash' ]]; then
	if [[ ! $(dpkg -l git-core 2> /dev/null) ]]; then
		apt-get install -qqy git-core
	fi
	git clone https://github.com/nuada/puppet
	cd puppet
fi

puppet apply --verbose --modulepath=modules $* manifests/site.pp
