#!/bin/bash
# Usage: curl https://raw.github.com/nuada/puppet/apply | bash -s

if [[ ! $(dpkg -l puppet 2> /dev/null) ]]; then
	. /etc/lsb-release
	wget http://apt.puppetlabs.com/puppetlabs-release-${DISTRIB_CODENAME}.deb
	dpkg -i puppetlabs-release-${DISTRIB_CODENAME}.deb
	rm -rf puppetlabs-release-${DISTRIB_CODENAME}.deb
	apt-get update
	apt-get -y install puppet
fi

# TODO Checkout from github if not running from repo

puppet apply --verbose --modulepath=modules $* manifests/site.pp
