alias dh='df -h'
alias g='gvim'
alias la="ls -a"
alias lh="ls -lh"
alias ll="ls -l"
alias l="ls"
alias resizealbum='mogrify -scale 1200x1200 -quality 95 -strip -monitor'
alias resizelab='mogrify -scale 1807x1807 -quality 95 -strip -monitor'
alias s="cd .."
alias v='view'
