#!/bin/bash
if [[ ! $1 ]]; then
	echo 'Usage: brightness <value>'
	echo -e '\tvalue - 0-1'
	exit 1
fi
max=$(cat /sys/class/backlight/intel_backlight/max_brightness)
val=$(echo "${max}*$1" | bc | cut -d . -f 1)
echo ${val} > /sys/class/backlight/intel_backlight/brightness
